### ISSUE TITLE
Table layout

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#265]
Geoff T asked about table overflow where the content of the table is generated elsewhere and includes urls. In this case a fixed layout with explicit column width was useful. Should o-table provide utility classes for a fixed layout, so build service users don't have to repeat this css?

```css
.o-table--example {
    table-layout: fixed;
}

.o-table--example td {
    overflow-wrap: break-word; // fallback for where "anywhere" is not supported
    overflow-wrap: anywhere;
}
```
