### ISSUE TITLE
Add `component` label to every `component` issue, &c

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#33]
Proposal: Add a `component` label to all issues on all components, a `service` label to all issues on services etc to improve the display of issues in the [GitHub Project Board](https://github.com/orgs/Financial-Times/projects/83?fullscreen=true).

This will also let us use the `filter cards` box in the top right of the projects page to filter by `label:component` &c

**Comment by notlee** [comment]
🙌 yes

**Comment by JakeChampion** [comment]
This can be done via a GitHub Action using the labeler action like so:

Create a file named `.github/labeler.yml` with the contents in the code block below.
```yml
# .github/labeler.yml

# Add 'component' label whenever any file is modified
component:
  - ./*
  - ./**/*
```

Create a file named `.github/workflows/labeler.yml` with the contents of the code block below:
```yml
#.github/workflows/labeler.yml

name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```
