### ISSUE TITLE
o-expander:  focus/tab order does not follow user expectations - ID: DAC_Focus_Order_03

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#513]
# Issue
This is from page 54 of the [audit report](https://drive.google.com/file/d/17wq6b0CIX41RA4muBFDzUDxE0-qzHBIH/view)

Issue can be found on: <https://www.ft.com/__origami/service/build/v3/demo?component=o-expander%406.0.0&demo=Toggle+State&system_code=origami-repo-data&brand=master>

When the toggle button is activated, the information is added above the toggle button. This creates an illogical focus order. This issue would particularly affect screen reader users who may not be able to identify that the information has been added above the button and would need to use the up arrow key to navigate back to the list to access the information added to the page.

# Proposed Solution:
Add a visually-hidden span to the button’ label to inform screen reader users that the information is added above the button.
Example:
```html
 <button class="o-expander__toggle" aria-controls="o-expander__toggle--0" aria- expanded="true">
	Toggle<span class="visually-hidden">content will be added above button</span>
</button>
```
```css
.visually-hidden {
	clip: rect(0 0 0 0);
	clip-path: inset(50%); 
	height: 1px; 
	overflow: hidden; 
	position: absolute; 
	white-space: nowrap; 
	width: 1px;
}
```
