### ISSUE TITLE
automerge dev dependencies on pass

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#55]
Dependabot deluge has me down. Proposal to auto merge all dev dependency minor and patch updates when Dependabot PR checks pass.

Example dev dependencies:
- eslint-config-origami-component
- origami-ci-tools
- stylelint-config-origami-component
- @swc/core
- scrumple
- snyk
- eslint
- proclaim
- sinon
- mocha

**why?**
This will reduce issue noise and the burden of merging many dependency PRs regularly.

**why not production dependencies?**
We could add production dependencies in the future provided we configure Dependabot to also:
1. add a release tag
2. only merge during business hours 

Doing so would allow us to respond to any problems and track an issue to a specific release/dependency. For now I propose we don't do this and manually review production dependency changes and see how the volume of Dependabot PRs feel.

**how?**
Add the following to `.dependabot/config.yml` in each repository. Provided automerged updates are enabled at the account level (from account settings in our dashboard):

```
version: 1
update_configs:
  - package_manager: "javascript"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
```

**Comment by JakeChampion** [comment]
Yes please :-D

**Comment by chee** [comment]
yes

**Comment by notlee** [comment]
Cool! I'll do that. @JakeChampion could you check automerge is enabled on our account? I'm not sure I have permission. I think the link to our dashboard is https://app.dependabot.com/ looking at [the docs](https://dependabot.com/docs/config-file/#automerged_updates).

**Comment by chee** [comment]
![image](https://user-images.githubusercontent.com/178266/83007161-cee95b80-a002-11ea-8858-075e5874cfa3.png)

**Comment by notlee** [comment]
Oh! Sorry I do have access, thanks @chee! Where are you seeing that? I see under the ft org its disabled, is that screenshot you enabling it?

**Comment by chee** [comment]
oh yeas, i was enabling it but i hadn'tclicked the big blue button yet

**Comment by chee** [comment]
i clicked the big blue button now

**Comment by notlee** [comment]
Oh my proposed config is invalid, you have to define directory and schedule:

```
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
```
